In [112]:
import pandas as pd
import numpy as np

iris = pd.read_csv('Data_Set/iris.csv')
species = ['setosa', 'versicolor', 'virginica']

In [122]:
# m = num of training examples, n = num of features, c = num of classes
m, n, c = iris.shape[0], iris.shape[1] - 1, len(species)

def oneVsAllConvert(h, From, To):
    for i in range(m):
        if h[i][-1] == From:
            h[i][-1] = To

# list to store the modified data for all the hypothesis
iris_h = []
for i in range(c):
    iris_h.append(np.array(iris, dtype = 'float32'))

# modify the datatset as first species to be 0, rest to be 1, one vs all 
oneVsAllConvert(iris_h[0], 2, 1)

# second species to be 0, rest to be 1
oneVsAllConvert(iris_h[1], 0, 2)
oneVsAllConvert(iris_h[1], 1, 0)
oneVsAllConvert(iris_h[1], 2, 1)

# third species to be 0, rest to be 1
oneVsAllConvert(iris_h[2], 0, 1)
oneVsAllConvert(iris_h[2], 2, 0)

In [114]:
def normalize(x):
    return (x - x.mean(axis = 0)) / x.std(axis = 0)

x_0 = iris_h0[:, :-1]
x_0 = normalize(x_0)
y_0 = iris_h0[:, -1]

x_1 = iris_h1[:, :-1]
x_1 = normalize(x_1)
y_1 = iris_h1[:, -1]

x_2 = iris_h2[:, :-1]
x_2 = normalize(x_2)
y_2 = iris_h2[:, -1]

[[-9.0068120e-01  1.0320569e+00 -1.3412726e+00 -1.3129768e+00]
 [-1.1430167e+00 -1.2495793e-01 -1.3412726e+00 -1.3129768e+00]
 [-1.3853527e+00  3.3784813e-01 -1.3981384e+00 -1.3129768e+00]
 [-1.5065205e+00  1.0644482e-01 -1.2844070e+00 -1.3129768e+00]
 [-1.0218489e+00  1.2634597e+00 -1.3412726e+00 -1.3129768e+00]
 [-5.3717732e-01  1.9576690e+00 -1.1706755e+00 -1.0500308e+00]
 [-1.5065205e+00  8.0065417e-01 -1.3412726e+00 -1.1815038e+00]
 [-1.0218489e+00  8.0065417e-01 -1.2844070e+00 -1.3129768e+00]
 [-1.7488561e+00 -3.5636067e-01 -1.3412726e+00 -1.3129768e+00]
 [-1.1430167e+00  1.0644482e-01 -1.2844070e+00 -1.4444497e+00]
 [-5.3717732e-01  1.4948629e+00 -1.2844070e+00 -1.3129768e+00]
 [-1.2641845e+00  8.0065417e-01 -1.2275413e+00 -1.3129768e+00]
 [-1.2641845e+00 -1.2495793e-01 -1.3412726e+00 -1.4444497e+00]
 [-1.8700238e+00 -1.2495793e-01 -1.5118699e+00 -1.4444497e+00]
 [-5.2505739e-02  2.1890717e+00 -1.4550041e+00 -1.3129768e+00]
 [-1.7367408e-01  3.1146839e+00 -1.2844070e+00 -1.05003

In [115]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def error(w0, w1, w2, w3, w4, x, y):
    cost = 0
    for i in range(len(y)):
        hypothesis = sigmoid(w0 + w1 * x[i][0] + w2 * x[i][1] + w3 * x[i][2] + w4 * x[i][3])
        cost += (y[i] * np.log(hypothesis) + (1 - y[i]) * np.log(1 - hypothesis))

    return -cost / len(y)

def gradient_descent(alpha, w0, w1, w2, w3, w4, x, y):
    temp0, temp1, temp2, temp3, temp4 = 0, 0, 0, 0, 0
    for i in range(len(y)):
        hypothesis = sigmoid(w0 + w1 * x[i][0] + w2 * x[i][1] + w3 * x[i][2] + w4 * x[i][3]) - y[i]
        temp0 += hypothesis
        temp1 += (hypothesis * x[i][0])
        temp2 += (hypothesis * x[i][1])
        temp3 += (hypothesis * x[i][2])
        temp4 += (hypothesis * x[i][3])
    
    w0 -= (alpha * temp0 / len(y))
    w1 -= (alpha * temp1 / len(y))
    w2 -= (alpha * temp2 / len(y))
    w3 -= (alpha * temp3 / len(y))
    w4 -= (alpha * temp4 / len(y))

    return w0, w1, w2, w3, w4

In [116]:
import random
theta = []
theta_0 = []
theta_1 = []
theta_2 = []

w0, w1, w2, w3, w4 = random.random(), random.random(), random.random(), random.random(), random.random()
# append w0, w1, w2, w3, w4 to theta_0
theta_0.append(w0)
theta_0.append(w1)
theta_0.append(w2)
theta_0.append(w3)
theta_0.append(w4)

w0, w1, w2, w3, w4 = random.random(), random.random(), random.random(), random.random(), random.random()
theta_1.append(w0)
theta_1.append(w1)
theta_1.append(w2)
theta_1.append(w3)
theta_1.append(w4)

w0, w1, w2, w3, w4 = random.random(), random.random(), random.random(), random.random(), random.random()
theta_2.append(w0)
theta_2.append(w1)
theta_2.append(w2)
theta_2.append(w3)
theta_2.append(w4)

theta.append(theta_0)
theta.append(theta_1)
theta.append(theta_2)

for _ in range(200):
    
    theta[0] = gradient_descent(0.8, theta[0][0], theta[0][1], theta[0][2], theta[0][3], theta[0][4], x_0, y_0)
    theta[1] = gradient_descent(0.8, theta[1][0], theta[1][1], theta[1][2], theta[1][3], theta[1][4], x_1, y_1)
    theta[2] = gradient_descent(0.8, theta[2][0], theta[2][1], theta[2][2], theta[2][3], theta[2][4], x_2, y_2)

    print('First:', error(theta[0][0], theta[0][1], theta[0][2], theta[0][3], theta[0][4], x_0, y_0))
    print('Second:', error(theta[1][0], theta[1][1], theta[1][2], theta[1][3], theta[1][4], x_1, y_1))
    print('Third:', error(theta[2][0], theta[2][1], theta[2][2], theta[2][3], theta[2][4], x_2, y_2))
    print('\n')

    

First: 0.20665188969720502
Second: 0.5852195329754377
Third: 0.7815647628543527


First: 0.16702562361275738
Second: 0.5523140227882527
Third: 0.5398086467390427


First: 0.14159080320333797
Second: 0.5397082544385793
Third: 0.45005785285783473


First: 0.12361322313490058
Second: 0.5334327372525263
Third: 0.401838120067638


First: 0.11010040004727692
Second: 0.5294183637753856
Third: 0.3700874907186734


First: 0.09950668206296077
Second: 0.5263865478969775
Third: 0.34696730608862675


First: 0.09094345890166977
Second: 0.5238904444577442
Third: 0.32915324294682274


First: 0.08385840424221054
Second: 0.5217481982788292
Third: 0.3149107352040357


First: 0.07788750797074623
Second: 0.519869978660302
Third: 0.30320826024161707


First: 0.07277976129973161
Second: 0.5182020917378676
Third: 0.2933803694353603


First: 0.06835574561577787
Second: 0.5167075753660586
Third: 0.28497453322043675


First: 0.06448341542417256
Second: 0.5153587368931446
Third: 0.27767152225582586


First: 0.061

In [117]:
iris = np.array(iris, dtype = 'float32')

iris_x = iris[:, :-1]
iris_x = normalize(iris_x)

for i in range(len(iris_x)):
    # calculate theta0, theta1, theta2

    theta0 = sigmoid(theta[0][0] + theta[0][1] * iris_x[i][0] + theta[0][2] * iris_x[i][1] + theta[0][3] * iris_x[i][2] + theta[0][4] * iris_x[i][3])
    theta1 = sigmoid(theta[1][0] + theta[1][1] * iris_x[i][0] + theta[1][2] * iris_x[i][1] + theta[1][3] * iris_x[i][2] + theta[1][4] * iris_x[i][3])
    theta2 = sigmoid(theta[2][0] + theta[2][1] * iris_x[i][0] + theta[2][2] * iris_x[i][1] + theta[2][3] * iris_x[i][2] + theta[2][4] * iris_x[i][3])

    print(theta0, theta1, theta2)

    if min(theta0, theta1, theta2) == theta0:
        label = 0
    elif min(theta0, theta1, theta2) == theta1:
        label = 1
    else:
        label = 2

    # print the label and the actual label
    print('Predicted:', label, 'Actual:', iris[i][4])

0.0014923868272844682 0.9128879089535828 0.9999973124938499
Predicted: 0 Actual: 0.0
0.009833301323441224 0.6926392145617015 0.9999956502807202
Predicted: 0 Actual: 0.0
0.002734856941507288 0.8240360826631185 0.9999967574126486
Predicted: 0 Actual: 0.0
0.004636644858861854 0.7557085547345656 0.999994941428064
Predicted: 0 Actual: 0.0
0.0008330527902059758 0.9361522412011692 0.9999974773453193
Predicted: 0 Actual: 0.0
0.0010635694811917337 0.9756327393842003 0.9999925008879121
Predicted: 0 Actual: 0.0
0.0015098864088774677 0.9084504051471554 0.9999947153076245
Predicted: 0 Actual: 0.0
0.002247891247484095 0.8802190033059337 0.9999964526869909
Predicted: 0 Actual: 0.0
0.007342465501128895 0.6453489697531583 0.9999946621053074
Predicted: 0 Actual: 0.0
0.005292016933548512 0.7127969963164396 0.9999970585715537
Predicted: 0 Actual: 0.0
0.0010884553868458458 0.9458187848623245 0.9999975124547109
Predicted: 0 Actual: 0.0
0.001890853044218167 0.878195625085762 0.9999956050089923
Predicted: 0 A